<a href="https://colab.research.google.com/github/prakash-2736/ML_workshop/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#1. Perform arithmetic operations on NumPy arrays.

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])


add = a + b
sub = a - b
mul = a * b
div = a / b

print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)


Addition: [2 4 6]
Subtraction: [0 0 0]
Multiplication: [1 4 9]
Division: [1. 1. 1.]


In [ ]:
#2. Write a script to compute the mean and standard deviation of a NumPy array
data = np.array([10, 20, 30, 40, 50])


mean = np.mean(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Standard Deviation:", std_dev)


Mean: 30.0
Standard Deviation: 14.142135623730951


In [ ]:
#3. Create a NumPy array of integers from 10 to 50 with a step size of 5.
array = np.arange(10, 51, 5)
print("Array:", array)

Array: [10 15 20 25 30 35 40 45 50]


In [ ]:
#4. Reshape the array into a 2x4 matrix.
array = array[:8]
reshaped_arr = array.reshape(2, 4)
print("Reshaped Array:\n", reshaped_arr)

Reshaped Array:
 [[10 15 20 25]
 [30 35 40 45]]


In [ ]:
#5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
# • Extract the sub-matrix containing the last two rows and first two columns.
# • Replace all elements greater than 4 with 0.
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_matrix = array[1:, :2]

array[array > 4] = 0

print("Sub matrix:\n", sub_matrix)
print("Modified Array:\n", array)

Sub matrix:
 [[4 0]
 [0 0]]
Modified Array:
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


In [ ]:
# 6. Create two 1D arrays:
# • a = np.array([1, 2, 3])
# • b = np.array([4, 5, 6])
# • Perform element-wise addition, multiplication, and division.


a = np.array([1, 2, 3])
b = np.array([1, 2, 3])


add = a + b

mul = a * b
div = a / b

print("Addition:", add)
print("Multiplication:", mul)
print("Division:", div)

Addition: [2 4 6]
Multiplication: [1 4 9]
Division: [1. 1. 1.]


In [ ]:
# 7. Create a random NumPy array of size (4, 4). Compute:
# • Mean of each column.
# • Maximum value of the entire array.
# • Sum of all elements.


ran_array = np.random.rand(4, 4) * 100
# ran_array = np.random.randint(1, 101, (4, 4))
print(ran_array)
col_mean = np.mean(ran_array, axis=0)
max_value = np.max(ran_array)
total_sum = np.sum(ran_array)

print("Column Means:", col_mean)
print("Maximum Value:", max_value)
print("Sum of All Elements:", total_sum)


[[77.33121037 65.16409631 70.99070485 97.92722396]
 [94.68838346 13.82890827 60.92435102 43.40895352]
 [92.14099669 10.39646805 44.12972306 70.00984776]
 [79.4026046  86.50642729 20.40823379 35.21686806]]
Column Means: [85.89079878 43.97397498 49.11325318 61.64072332]
Maximum Value: 97.92722396196089
Sum of All Elements: 962.4750010787598


In [ ]:
# 8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
# the result by 2.



array = np.array([[1, 2, 3, 4], [5,6,7,8]])

result_array = (array + 10) * 2
print("Modified Array:\n", result_array)

Modified Array:
 [[22 24 26 28]
 [30 32 34 36]]


In [ ]:
# 9. Perform advanced slicing and indexing on a 3D array.
# Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
# 1 to 100. Perform the following:
# • Extract the second "layer" (i.e., the second 2D array) in the first dimension.
# • Extract the first two rows and the last three columns from each "layer."
# • Replace all elements divisible by 3 with -1.

array = np.random.randint(1, 101, (3, 4, 5))
# print(arr)
second_layer = array[1]

sub_matrix = array[:, :2, -3:]

array[array % 3 == 0] = -1

print("Second Layer:\n", second_layer)
print("Sub-matrix:\n", sub_matrix)
print("Modified Array:\n", array)

Second Layer:
 [[25 31 -1 -1 38]
 [68 38 20 -1 14]
 [-1 47 -1 68 94]
 [49  8 -1 -1 83]]
Sub-matrix:
 [[[31 28 -1]
  [13 -1 97]]

 [[-1 -1 38]
  [20 -1 14]]

 [[56 92 -1]
  [58 -1 -1]]]
Modified Array:
 [[[20 38 31 28 -1]
  [-1 -1 13 -1 97]
  [-1 68 52  8 94]
  [-1 -1 53 -1 61]]

 [[25 31 -1 -1 38]
  [68 38 20 -1 14]
  [-1 47 -1 68 94]
  [49  8 -1 -1 83]]

 [[58 -1 56 92 -1]
  [25 20 58 -1 -1]
  [89 41 -1 94 -1]
  [-1 28 61 43 79]]]


In [ ]:
# 10. Work with broadcasting and advanced operations in NumPy.
#  Create a NumPy array arr of shape (3, 3) with random integers between
#  1 and 20. Perform the following:
# • Subtract the mean of each row from its respective elements (row-wise
# normalization).
# • Create a new array by squaring all the elements in arr.
# • Find the indices of the top 3 maximum values in the entire array


arr = np.random.randint(1, 21, (3, 3))

row_means = np.mean(arr, axis=1, keepdims=True)
normalized_arr = arr - row_means

squared_arr = arr ** 2


flattened_indices = np.argsort(arr.ravel())[-3:]
# indices = np.unravel_index(flattened_indices, arr.shape)
indices = [np.unravel_index(idx, arr.shape) for idx in flattened_indices]

print("Original Array:\n", arr)
print("Row-wise Normalized Array:\n", normalized_arr)
print("Squared Array:\n", squared_arr)
print("Indices of Top 3 Maximum Values:", indices)


Original Array:
 [[10 17 17]
 [18  6  4]
 [17 19  8]]
Row-wise Normalized Array:
 [[-4.66666667  2.33333333  2.33333333]
 [ 8.66666667 -3.33333333 -5.33333333]
 [ 2.33333333  4.33333333 -6.66666667]]
Squared Array:
 [[100 289 289]
 [324  36  16]
 [289 361  64]]
Indices of Top 3 Maximum Values: [(2, 0), (1, 0), (2, 1)]
